name:                dfalang
version:             0.1.0.0
github:              "borisPristupa/dfalang"
license:             MIT
author:              "Boris Pristupa"
maintainer:          "boris.pristupa@gmail.com"
copyright:           "Boris Pristupa"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/borisPristupa/dfalang#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - containers

executables:
  dfalang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dfalang
    - optparse-applicative
    - filepath
    - containers

tests:
  dfalang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dfalang
    - containers
